from pathlib import Path
from openai import OpenAI
import pygame
import os
from __main__ import __name__
import sys

class TextSpeaker():
    """
    A class that converts text to speech and plays the audio using pygame.

    Usage:
    - To convert and play a single text, run the script with the text as an argument:
        `python speaker.py "Hello, world!"`
    - To convert and play multiple texts in a loop, run the script with the `--loop` flag:
        `python speaker.py --loop`
    """
    def __init__(self) -> None:
        pygame.mixer.init()
        # Get API key
        path = os.path.join(os.getcwd(), 'settings', 'key.txt')
        try:
            with open(path, 'r') as f:
                api_key = f.read().strip()
        except:
            print('key error')
        self.client = OpenAI(api_key=api_key)

    def getAudio(self, speech_string):
        """
        Converts the given text to speech and saves the audio to a file.

        Args:
        - speech_string (str): The text to convert to speech.
        """
        speech_file_path = Path(__file__).parent / "speech.mp3"
        response = self.client.audio.speech.create(
        model="tts-1",
        voice="alloy",
        input=speech_string
        )

        response.stream_to_file(speech_file_path)


    def playAudio(self):
        """
        Plays the audio file generated by `getAudio()` using pygame.
        """
        speech_file_path = Path(__file__).parent / "speech.mp3"
        pygame.mixer.music.load(str(speech_file_path))
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy() == True:
            continue

if __name__ == "__main__":
    obj = TextSpeaker()
    if len(sys.argv) > 1 and sys.argv[1] == "--loop":
        while True:
            text = input("Enter text to speak: ")
            try:
                obj.getAudio(text)
                obj.playAudio()
            except Exception as e:
                print(f"Error: {e}")
    elif len(sys.argv) > 1:
        text = " ".join(sys.argv[1:])
        try:
            obj.getAudio(text)
            obj.playAudio()
        except Exception as e:
            print(f"Error: {e}")
    else:
        print("Usage: python speaker.py [text] or python speaker.py --loop")
